/** 工具 API 名 → 侧栏/对话中展示的中文标签 */
const TOOL_DISPLAY_NAMES: Record<string, string> = {
  get_current_time: '获取当前时间',
  get_stock_basic: '查询股票基本信息',
  get_daily_price: '查询日线行情',
  get_realtime_price: '查询实时价格',
  get_new_share_quotes: '查询新股行情',
  get_daily_basic: '查询估值指标',
  get_income_statement: '查询利润表',
  get_index_daily: '查询指数行情',
  get_hk_stock_basic: '查询港股基本信息',
  get_hk_daily_price: '查询港股日线',
  get_hk_realtime_price: '查询港股实时价',
  get_us_stock_basic: '查询美股基本信息',
  get_us_daily_price: '查询美股日线',
  get_us_realtime_price: '查询美股实时价',
  get_etf_basic: '查询 ETF 基本信息',
  get_etf_daily_price: '查询 ETF 日线',
  get_cb_basic: '查询可转债基本信息',
  get_cb_daily_price: '查询可转债日线',
  get_futures_basic: '查询期货基本信息',
  get_futures_daily_price: '查询期货日线',
  get_macro_gdp: '查询 GDP 数据',
  get_macro_cpi: '查询 CPI 数据',
  get_macro_m2: '查询 M2 数据',
  get_macro_interest_rate: '查询利率数据',
  get_global_index_comparison: '对比全球指数',
  get_moneyflow: '查询资金流向',
  get_hsgt_top10: '查询沪深港通十大成交',
  get_limit_list: '查询涨跌停',
  get_top_list: '查询龙虎榜',
  get_forecast: '查询业绩预告',
  get_concept_detail: '查询概念板块',
  get_technical_indicators: '计算技术指标',
  get_technical_patterns: '识别技术形态',
  screen_stocks: '条件选股',
  get_long_tail_stocks: '长尾选股',
  run_backtest: '策略回测',
  add_price_alert: '设置价格提醒',
  list_alerts: '查看价格提醒',
  remove_alert: '删除价格提醒',
  update_alert: '更新价格提醒',
  query_news: '全量新闻查询',
  query_notified_news: '查询已推送新闻',
  create_news_subscription: '创建新闻订阅',
  list_news_subscriptions: '查看新闻订阅',
  update_news_subscription: '更新新闻订阅',
  pause_news_subscription: '暂停新闻订阅',
  enable_news_subscription: '启用新闻订阅',
  delete_news_subscription: '删除新闻订阅',
  refresh_news: '刷新新闻',
  add_portfolio_position: '添加持仓',
  remove_portfolio_position: '移除持仓',
  get_portfolio_status: '查询持仓',
  clear_portfolio: '清空持仓',
  add_watchlist: '加入自选',
  list_watchlist: '查看自选',
  remove_watchlist: '移出自选',
  update_user_profile: '更新用户画像',
  get_user_profile: '查询用户画像'
}

export function toolDisplayName(toolName: string): string {
  return TOOL_DISPLAY_NAMES[toolName] ?? toolName
}
